In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/summer-analytics-mid-hackathon/hacktest.csv
/kaggle/input/summer-analytics-mid-hackathon/hacktrain.csv

In [2]:
df = pd.read_csv("/kaggle/input/summer-analytics-mid-hackathon/hacktrain.csv")
df

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Unnamed: 0,ID,class,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,0,1,water,637.5950,658.668,-1882.030,-1924.36,997.904,-1739.990,630.087,...,NaN,-1043.160,-1942.490,267.138,NaN,NaN,211.328,-2203.020,-1180.19,433.906
1,1,2,water,634.2400,593.705,-1625.790,-1672.32,914.198,-692.386,707.626,...,NaN,-933.934,-625.385,120.059,364.858,476.972,220.878,-2250.000,-1360.56,524.075
2,3,4,water,58.0174,-1599.160,NaN,-1052.63,NaN,-1564.630,NaN,...,-1025.880,368.622,NaN,-1227.800,304.621,NaN,369.214,-2202.120,NaN,-1343.550
3,4,5,water,72.5180,NaN,380.436,-1256.93,515.805,-1413.180,-802.942,...,-1813.950,155.624,NaN,-924.073,432.150,282.833,298.320,-2197.360,NaN,-826.727
4,7,8,water,1136.4400,NaN,NaN,1647.83,1935.800,NaN,2158.980,...,1535.000,1959.430,-279.317,-384.915,-113.406,1020.720,1660.650,-116.801,-568.05,-1357.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,10537,10538,impervious,1207.7000,984.620,NaN,1166.25,937.478,1072.700,823.896,...,1117.740,1176.600,1044.110,NaN,369.082,465.843,362.882,979.795,NaN,433.659
7996,10538,10539,impervious,2170.3500,1419.720,1361.000,1478.71,983.911,1262.110,1422.860,...,984.634,2128.970,1379.660,NaN,762.633,485.204,446.724,771.747,1589.06,506.936
7997,10541,10542,impervious,1895.6800,1454.740,NaN,1033.56,1930.380,1057.150,1471.600,...,888.408,2093.020,1232.110,1190.830,1441.460,1170.880,1095.000,1818.650,2501.72,1247.770
7998,10542,10543,impervious,3465.7400,1283.320,413.412,4391.05,1146.820,4473.050,1614.750,...,5833.760,4047.320,4515.800,433.177,277.296,744.143,NaN,3759.710,NaN,388.346
7999,10544,10545,impervious,6941.1900,1667.870,5084.780,NaN,1588.950,5978.190,NaN,...,7352.570,3289.860,3729.150,1994.980,NaN,5299.900,NaN,5983.130,1249.71,2424.230

In [3]:
df.isnull().sum()

Unnamed: 0       0
ID               0
class            0
20150720_N     560
20150602_N    1200
20150517_N     800
20150501_N     960
20150415_N     480
20150330_N    1120
20150314_N     720
20150226_N    1360
20150210_N     640
20150125_N    1040
20150109_N     880
20141117_N    1280
20141101_N     400
20141016_N    1440
20140930_N     800
20140813_N     560
20140626_N    1600
20140610_N     480
20140525_N     720
20140509_N     880
20140423_N    1760
20140407_N     640
20140322_N    1120
20140218_N    1440
20140202_N     560
20140117_N    1200
20140101_N     400
dtype: int64

In [4]:
df.fillna(df.median(numeric_only=True), inplace=True)
df.isnull().sum()

Unnamed: 0    0
ID            0
class         0
20150720_N    0
20150602_N    0
20150517_N    0
20150501_N    0
20150415_N    0
20150330_N    0
20150314_N    0
20150226_N    0
20150210_N    0
20150125_N    0
20150109_N    0
20141117_N    0
20141101_N    0
20141016_N    0
20140930_N    0
20140813_N    0
20140626_N    0
20140610_N    0
20140525_N    0
20140509_N    0
20140423_N    0
20140407_N    0
20140322_N    0
20140218_N    0
20140202_N    0
20140117_N    0
20140101_N    0
dtype: int64

In [5]:
#we have uhhh scaled NDVI values so unscale them, first we filter the dataset
ndvi_cols = df.filter(like='_N').columns

#checking shape of filtered ndvi columns
print(ndvi_cols.shape)

df[ndvi_cols]

(27,)

,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,20150125_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,637.5950,658.668,-1882.030,-1924.360,997.904,-1739.990,630.087,5831.120,-1325.640,-944.084,...,5484.905,-1043.160,-1942.490,267.138,1183.715,1599.385,211.3280,-2203.020,-1180.19,433.906
1,634.2400,593.705,-1625.790,-1672.320,914.198,-692.386,707.626,-1670.590,-1408.640,-989.285,...,5484.905,-933.934,-625.385,120.059,364.858,476.972,220.8780,-2250.000,-1360.56,524.075
2,58.0174,-1599.160,4672.000,-1052.630,1586.240,-1564.630,2802.010,729.790,-3162.140,6518.745,...,-1025.880,368.622,2633.695,-1227.800,304.621,1599.385,369.2140,-2202.120,1521.21,-1343.550
3,72.5180,5513.375,380.436,-1256.930,515.805,-1413.180,-802.942,683.254,-2829.400,-1267.540,...,-1813.950,155.624,2633.695,-924.073,432.150,282.833,298.3200,-2197.360,1521.21,-826.727
4,1136.4400,5513.375,4672.000,1647.830,1935.800,5742.485,2158.980,5831.120,1242.870,-2646.050,...,1535.000,1959.430,-279.317,-384.915,-113.406,1020.720,1660.6500,-116.801,-568.05,-1357.140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,1207.7000,984.620,4672.000,1166.250,937.478,1072.700,823.896,943.698,944.619,1040.990,...,1117.740,1176.600,1044.110,2624.125,369.082,465.843,362.8820,979.795,1521.21,433.659
7996,2170.3500,1419.720,1361.000,1478.710,983.911,1262.110,1422.860,1401.970,1372.680,1142.340,...,984.634,2128.970,1379.660,2624.125,762.633,485.204,446.7240,771.747,1589.06,506.936
7997,1895.6800,1454.740,4672.000,1033.560,1930.380,1057.150,1471.600,5831.120,2693.630,2377.550,...,888.408,2093.020,1232.110,1190.830,1441.460,1170.880,1095.0000,1818.650,2501.72,1247.770
7998,3465.7400,1283.320,413.412,4391.050,1146.820,4473.050,1614.750,770.469,4497.485,2676.000,...,5833.760,4047.320,4515.800,433.177,277.296,744.143,969.7115,3759.710,1521.21,388.346
7999,6941.1900,1667.870,5084.780,5810.755,1588.950,5978.190,2802.010,3068.030,6471.470,7150.420,...,7352.570,3289.860,3729.150,1994.980,1183.715,5299.900,969.7115,5983.130,1249.71,2424.230

In [6]:
#now we need to unscale this value, because theoretically it should be between -1 to 1,
#but it seems to be scaled up as to help them be stored as integers

df[ndvi_cols] = df[ndvi_cols]/10000
df[ndvi_cols]

,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,20150125_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,0.063759,0.065867,-0.188203,-0.192436,0.099790,-0.173999,0.063009,0.583112,-0.132564,-0.094408,...,0.548490,-0.104316,-0.194249,0.026714,0.118372,0.159939,0.021133,-0.220302,-0.118019,0.043391
1,0.063424,0.059371,-0.162579,-0.167232,0.091420,-0.069239,0.070763,-0.167059,-0.140864,-0.098929,...,0.548490,-0.093393,-0.062538,0.012006,0.036486,0.047697,0.022088,-0.225000,-0.136056,0.052408
2,0.005802,-0.159916,0.467200,-0.105263,0.158624,-0.156463,0.280201,0.072979,-0.316214,0.651875,...,-0.102588,0.036862,0.263369,-0.122780,0.030462,0.159939,0.036921,-0.220212,0.152121,-0.134355
3,0.007252,0.551338,0.038044,-0.125693,0.051580,-0.141318,-0.080294,0.068325,-0.282940,-0.126754,...,-0.181395,0.015562,0.263369,-0.092407,0.043215,0.028283,0.029832,-0.219736,0.152121,-0.082673
4,0.113644,0.551338,0.467200,0.164783,0.193580,0.574249,0.215898,0.583112,0.124287,-0.264605,...,0.153500,0.195943,-0.027932,-0.038492,-0.011341,0.102072,0.166065,-0.011680,-0.056805,-0.135714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,0.120770,0.098462,0.467200,0.116625,0.093748,0.107270,0.082390,0.094370,0.094462,0.104099,...,0.111774,0.117660,0.104411,0.262412,0.036908,0.046584,0.036288,0.097979,0.152121,0.043366
7996,0.217035,0.141972,0.136100,0.147871,0.098391,0.126211,0.142286,0.140197,0.137268,0.114234,...,0.098463,0.212897,0.137966,0.262412,0.076263,0.048520,0.044672,0.077175,0.158906,0.050694
7997,0.189568,0.145474,0.467200,0.103356,0.193038,0.105715,0.147160,0.583112,0.269363,0.237755,...,0.088841,0.209302,0.123211,0.119083,0.144146,0.117088,0.109500,0.181865,0.250172,0.124777
7998,0.346574,0.128332,0.041341,0.439105,0.114682,0.447305,0.161475,0.077047,0.449748,0.267600,...,0.583376,0.404732,0.451580,0.043318,0.027730,0.074414,0.096971,0.375971,0.152121,0.038835
7999,0.694119,0.166787,0.508478,0.581075,0.158895,0.597819,0.280201,0.306803,0.647147,0.715042,...,0.735257,0.328986,0.372915,0.199498,0.118372,0.529990,0.096971,0.598313,0.124971,0.242423

In [7]:
df
#checking the dataset

,Unnamed: 0,ID,class,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
0,0,1,water,0.063759,0.065867,-0.188203,-0.192436,0.099790,-0.173999,0.063009,...,0.548490,-0.104316,-0.194249,0.026714,0.118372,0.159939,0.021133,-0.220302,-0.118019,0.043391
1,1,2,water,0.063424,0.059371,-0.162579,-0.167232,0.091420,-0.069239,0.070763,...,0.548490,-0.093393,-0.062538,0.012006,0.036486,0.047697,0.022088,-0.225000,-0.136056,0.052408
2,3,4,water,0.005802,-0.159916,0.467200,-0.105263,0.158624,-0.156463,0.280201,...,-0.102588,0.036862,0.263369,-0.122780,0.030462,0.159939,0.036921,-0.220212,0.152121,-0.134355
3,4,5,water,0.007252,0.551338,0.038044,-0.125693,0.051580,-0.141318,-0.080294,...,-0.181395,0.015562,0.263369,-0.092407,0.043215,0.028283,0.029832,-0.219736,0.152121,-0.082673
4,7,8,water,0.113644,0.551338,0.467200,0.164783,0.193580,0.574249,0.215898,...,0.153500,0.195943,-0.027932,-0.038492,-0.011341,0.102072,0.166065,-0.011680,-0.056805,-0.135714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,10537,10538,impervious,0.120770,0.098462,0.467200,0.116625,0.093748,0.107270,0.082390,...,0.111774,0.117660,0.104411,0.262412,0.036908,0.046584,0.036288,0.097979,0.152121,0.043366
7996,10538,10539,impervious,0.217035,0.141972,0.136100,0.147871,0.098391,0.126211,0.142286,...,0.098463,0.212897,0.137966,0.262412,0.076263,0.048520,0.044672,0.077175,0.158906,0.050694
7997,10541,10542,impervious,0.189568,0.145474,0.467200,0.103356,0.193038,0.105715,0.147160,...,0.088841,0.209302,0.123211,0.119083,0.144146,0.117088,0.109500,0.181865,0.250172,0.124777
7998,10542,10543,impervious,0.346574,0.128332,0.041341,0.439105,0.114682,0.447305,0.161475,...,0.583376,0.404732,0.451580,0.043318,0.027730,0.074414,0.096971,0.375971,0.152121,0.038835
7999,10544,10545,impervious,0.694119,0.166787,0.508478,0.581075,0.158895,0.597819,0.280201,...,0.735257,0.328986,0.372915,0.199498,0.118372,0.529990,0.096971,0.598313,0.124971,0.242423

In [8]:
#done with the preprocessing part now we can move to modelling

#first step is to define our inputs

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

# Drop ID column
df.drop(columns=['ID'], inplace=True)

# Encode class column (if it's categorical)
label_encoder = LabelEncoder()
df['class'] = label_encoder.fit_transform(df['class'])

# Split into features and target
X = df.drop(columns=['class'])
y = df['class']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# Fit multinomial logistic regression
model = LogisticRegression(
    multi_class='multinomial',
    solver='lbfgs',
    max_iter=1000
)
model.fit(X_train, y_train)

# Predict on test set
y_pred = model.predict(X_test)

# Classification report with all original class labels
print(classification_report(
    y_test,
    y_pred,
    labels=list(range(len(label_encoder.classes_))),
    target_names=label_encoder.classes_
))

              precision    recall  f1-score   support

        farm       0.70      0.82      0.75       168
      forest       0.97      0.99      0.98      1232
       grass       1.00      0.05      0.10        39
  impervious       0.77      0.82      0.80       134
     orchard       0.00      0.00      0.00         6
       water       0.00      0.00      0.00        21

    accuracy                           0.92      1600
   macro avg       0.57      0.45      0.44      1600
weighted avg       0.91      0.92      0.90      1600

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [9]:
test_data = pd.read_csv("/kaggle/input/summer-analytics-mid-hackathon/hacktest.csv")
test_data.shape

(2845, 29)

In [10]:
ID=test_data['ID']
test_data.drop(['ID'],axis=1,inplace=True)

In [11]:
y_test = model.predict(test_data)

In [12]:
y_test

array([1, 1, 1, ..., 3, 3, 3])

In [13]:
y_decoded = label_encoder.inverse_transform(y_test)
y_decoded

array(['forest', 'forest', 'forest', ..., 'impervious', 'impervious',
       'impervious'], dtype=object)

In [14]:
result = pd.DataFrame({
    'ID': ID,
    'class': y_decoded
})

In [15]:
result

        ID       class
0        1      forest
1        2      forest
2        3      forest
3        4      forest
4        5      forest
...    ...         ...
2840  2841  impervious
2841  2842  impervious
2842  2843  impervious
2843  2844  impervious
2844  2845  impervious

[2845 rows x 2 columns]

In [16]:
result.to_csv("submission.csv", index=False)